# External Secrets Operator Setup
#
# Installation:
# helm repo add external-secrets https://charts.external-secrets.io
# helm install external-secrets external-secrets/external-secrets \
#   --namespace external-secrets-system \
#   --create-namespace
#
# This file configures ESO to sync secrets from Vault

---
# Service Account for ESO authentication
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: production
---
# Vault policy (apply in Vault)
# vault policy write production-app - <<EOF
# path "secret/data/production/*" {
#   capabilities = ["read", "list"]
# }
# EOF
#
# Vault Kubernetes role (apply in Vault)
# vault write auth/kubernetes/role/production-app \
#   bound_service_account_names=app-sa \
#   bound_service_account_namespaces=production \
#   policies=production-app \
#   ttl=1h

---
# SecretStore: Vault connection configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: production
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "production-app"
          serviceAccountRef:
            name: app-sa
---
# ExternalSecret: Sync database credentials from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: production
spec:
  refreshInterval: 1h  # Poll Vault every hour
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: db-credentials  # Kubernetes Secret name
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        # Template for database connection string
        DATABASE_URL: "postgresql://{{ .username }}:{{ .password }}@postgres:5432/mydb"
  data:
  - secretKey: username
    remoteRef:
      key: secret/data/production/database
      property: username
  - secretKey: password
    remoteRef:
      key: secret/data/production/database
      property: password
---
# ExternalSecret: Sync API keys from Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-keys
  namespace: production
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: vault-backend
  target:
    name: api-keys
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: secret/data/production/api-keys  # Fetch all keys from this path
---
# Application Deployment using synced secrets
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      serviceAccountName: app-sa
      containers:
      - name: app
        image: myapp:latest
        env:
        # Environment variables from Kubernetes Secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DATABASE_URL
        # Or mount entire secret as env vars
        envFrom:
        - secretRef:
            name: api-keys
---
# Verification Steps:
#
# 1. Create secrets in Vault
# vault kv put secret/production/database \
#   username=myuser \
#   password=mypassword
#
# vault kv put secret/production/api-keys \
#   stripe_key=sk_live_EXAMPLE \
#   sendgrid_key=SG.EXAMPLE
#
# 2. Check ExternalSecret status
# kubectl get externalsecret -n production
# kubectl describe externalsecret database-credentials -n production
#
# 3. Verify Kubernetes Secret created
# kubectl get secret db-credentials -n production
# kubectl get secret db-credentials -n production -o jsonpath='{.data.DATABASE_URL}' | base64 -d
#
# 4. Test secret refresh
# vault kv put secret/production/database username=newuser password=newpass
# # Wait up to refreshInterval (1 hour)
# kubectl get secret db-credentials -n production -o jsonpath='{.data.username}' | base64 -d
