name: Multi-Stage Security Pipeline

on:
  pull_request:
  push:
    branches: [main, develop]

env:
  IMAGE_NAME: myapp
  IMAGE_TAG: ${{ github.sha }}

jobs:
  # ============================================
  # Stage 1: Fast Security Checks (< 5 minutes)
  # ============================================
  secrets-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gitleaks Secret Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Semgrep SAST
        uses: semgrep/semgrep-action@v1
        with:
          config: >-
            p/security-audit
            p/owasp-top-ten
            p/secrets

  dependency-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4

      - name: Dependency Review
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: high
          deny-licenses: GPL-2.0, GPL-3.0

  # ============================================
  # Stage 2: Container Scanning
  # ============================================
  container-scan:
    runs-on: ubuntu-latest
    needs: [secrets-scan, sast-scan]
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: sarif
          output: trivy-results.sarif
          severity: HIGH,CRITICAL
          exit-code: 1
          ignore-unfixed: true

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results.sarif

      - name: Generate SBOM (CycloneDX)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --format cyclonedx \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            > sbom-cyclonedx.json

      - name: Generate SBOM (SPDX)
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            aquasec/trivy:latest image \
            --format spdx-json \
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
            > sbom-spdx.json

      - name: Upload SBOMs
        uses: actions/upload-artifact@v3
        with:
          name: sboms-${{ env.IMAGE_TAG }}
          path: |
            sbom-cyclonedx.json
            sbom-spdx.json
          retention-days: 90

      - name: Scan SBOM for compliance
        run: |
          docker run --rm \
            -v $(pwd):/workspace \
            aquasec/trivy:latest sbom \
            /workspace/sbom-cyclonedx.json \
            --severity HIGH,CRITICAL \
            --exit-code 1

  # ============================================
  # Stage 3: DAST (Staging Only)
  # ============================================
  dast-scan:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: container-scan
    steps:
      - uses: actions/checkout@v4

      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: https://staging.example.com
          fail_action: true
          cmd_options: '-a'

  # ============================================
  # Stage 4: Reporting and Notifications
  # ============================================
  security-report:
    runs-on: ubuntu-latest
    if: always()
    needs: [secrets-scan, sast-scan, container-scan]
    steps:
      - name: Download SBOM artifacts
        uses: actions/download-artifact@v3
        with:
          name: sboms-${{ env.IMAGE_TAG }}
        continue-on-error: true

      - name: Generate security summary
        run: |
          echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image:** ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
          echo "**Scan Date:** $(date)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          if [ -f sbom-cyclonedx.json ]; then
            COMPONENT_COUNT=$(jq '.components | length' sbom-cyclonedx.json)
            echo "**Components:** $COMPONENT_COUNT" >> $GITHUB_STEP_SUMMARY
          fi

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "- Secrets: ${{ needs.secrets-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- SAST: ${{ needs.sast-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Container: ${{ needs.container-scan.result }}" >> $GITHUB_STEP_SUMMARY

  notify-security-team:
    runs-on: ubuntu-latest
    if: failure()
    needs: [secrets-scan, sast-scan, container-scan]
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "Security scan failed for ${{ github.repository }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Security Scan Failed* :warning:\n\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Author:* ${{ github.actor }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Run"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
